import { Transaction, PayrollRecord, FraudAlert, StablecoinMetric, ComplianceReport } from './types';

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN-9842',
    date: '2026-05-25',
    amount: 145000,
    token: 'USDC',
    chain: 'Base',
    type: 'Inflow',
    description: 'B2B Client Invoice Payment - Acme Corp',
    sender: '0x3f5c...a71d',
    receiver: '0xSM_Treasury_Base',
    status: 'Completed',
    riskScore: 4,
  },
  {
    id: 'TXN-9841',
    date: '2026-05-24',
    amount: 52000,
    token: 'USDT',
    chain: 'Ethereum',
    type: 'Payroll',
    description: 'Core Engineering monthly payroll disbursements',
    sender: '0xSM_Treasury_Eth',
    receiver: '0x99a2...3f33',
    status: 'Completed',
    riskScore: 12,
  },
  {
    id: 'TXN-9840',
    date: '2026-05-23',
    amount: 250000,
    token: 'DAI',
    chain: 'Ethereum',
    type: 'Treasury Swap',
    description: 'Rebalance: Swapped DAI to USDC to reduce depeg exposure',
    sender: '0xSM_Treasury_Eth',
    receiver: '0xSM_Treasury_Eth',
    status: 'Completed',
    riskScore: 8,
  },
  {
    id: 'TXN-9839',
    date: '2026-05-22',
    amount: 1250,
    token: 'EURC',
    chain: 'Arbitrum',
    type: 'Outflow',
    description: 'Vendor Reimbursement - EU Servers (Hetzner)',
    sender: '0xSM_Treasury_Arb',
    receiver: '0x74ba...b902',
    status: 'Completed',
    riskScore: 2,
  },
  {
    id: 'TXN-9838',
    date: '2026-05-21',
    amount: 98000,
    token: 'PYUSD',
    chain: 'Solana',
    type: 'Inflow',
    description: 'Merchant Gateway settlement via PayPal Web3 API',
    sender: '0x77ae...bb11',
    receiver: '0xSM_Treasury_Sol',
    status: 'Completed',
    riskScore: 5,
  },
  {
    id: 'TXN-9837',
    date: '2026-05-20',
    amount: 15300,
    token: 'USDT',
    chain: 'Solana',
    type: 'Payroll',
    description: 'Freelance Design team monthly compensation',
    sender: '0xSM_Treasury_Sol',
    receiver: '0x4fbc...cc44',
    status: 'Completed',
    riskScore: 28, // Sourced from decentralized KYC risk API
  },
  {
    id: 'TXN-PEND-01',
    date: '2026-05-26',
    amount: 43000,
    token: 'USDT',
    chain: 'Ethereum',
    type: 'Outflow',
    description: 'Pending vendor payout for marketing agency retainer',
    sender: '0xSM_Treasury_Eth',
    receiver: '0x889a...b78a',
    status: 'Pending',
    riskScore: 47,
  },
  {
    id: 'TXN-FLAG-02',
    date: '2026-05-26',
    amount: 112000,
    token: 'USDC',
    chain: 'Arbitrum',
    type: 'Inflow',
    description: 'Anonymous smart contract deposit - Unidentified bridge contract',
    sender: '0x66bf...99a0',
    receiver: '0xSM_Treasury_Arb',
    status: 'Flagged',
    riskScore: 89,
  }
];

export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'EMP-101',
    name: 'Sarah Jenkins',
    role: 'VP Engineering',
    country: 'United States',
    salary: 14500,
    mainChain: 'Base',
    splitToken: 'USDC',
    status: 'Active',
    nextPayout: '2026-06-01',
  },
  {
    id: 'EMP-102',
    name: 'Hiroshi Tanaka',
    role: 'Lead Blockchain Architect',
    country: 'Japan',
    salary: 12800,
    mainChain: 'Solana',
    splitToken: 'USDC',
    status: 'Active',
    nextPayout: '2026-06-01',
  },
  {
    id: 'EMP-103',
    name: 'Andrei Volkov',
    role: 'Senior Rust Developer',
    country: 'Estonia',
    salary: 9500,
    mainChain: 'Arbitrum',
    splitToken: 'EURC',
    status: 'Active',
    nextPayout: '2026-06-01',
  },
  {
    id: 'EMP-104',
    name: 'Sofia Rodriguez',
    role: 'Frontend Architect',
    country: 'Argentina',
    salary: 8200,
    mainChain: 'Solana',
    splitToken: 'USDT',
    status: 'Active',
    nextPayout: '2026-06-01',
  },
  {
    id: 'EMP-105',
    name: 'David Kojo',
    role: 'DevOps Engineer',
    country: 'Ghana',
    salary: 6300,
    mainChain: 'Base',
    splitToken: 'USDC',
    status: 'Active',
    nextPayout: '2026-06-01',
  },
  {
    id: 'EMP-106',
    name: 'Elena Rostova',
    role: 'Product Designer (Contract)',
    country: 'Cyprus',
    salary: 5000,
    mainChain: 'Polygon',
    splitToken: 'USDT',
    status: 'Active',
    nextPayout: '2026-06-01',
  }
];

export const INITIAL_FRAUD_ALERTS: FraudAlert[] = [
  {
    id: 'FRD-109',
    date: '2026-05-26',
    transactionId: 'TXN-FLAG-02',
    entity: 'Tornado.Cash Multi-bridge 0x66bf...99a0',
    reason: 'Indirect exposure of funds to sanctioned contract protocol (L2 Tornado Cash Router via Optimism Bridge).',
    severity: 'Critical',
    riskScore: 92,
    status: 'Unresolved',
    chain: 'Arbitrum',
    confidence: 97,
  },
  {
    id: 'FRD-108',
    date: '2026-05-25',
    entity: '0x889a...b78a - Marketing Retainer Recipient',
    reason: 'Target payout address has zero historic transaction density and was funded original gas by a newly-created Sybil cluster.',
    severity: 'Medium',
    riskScore: 54,
    status: 'Investigating',
    chain: 'Ethereum',
    confidence: 84,
  },
  {
    id: 'FRD-107',
    date: '2026-05-24',
    transactionId: 'TXN-9837',
    entity: '0x4fbc...cc44 - Freelance Designer Wallet',
    reason: 'Multi-sig consensus warning: Recipient address matches smart wallet with proxy admin pointing to blacklisted jurisdiction.',
    severity: 'High',
    riskScore: 78,
    status: 'Resolved',
    chain: 'Solana',
    confidence: 91,
  },
  {
    id: 'FRD-106',
    date: '2026-05-22',
    entity: '0xSM_Treasury_Base Admin Action',
    reason: 'Sequential non-incremental nonce shift detected in signature cluster - resolved as internal safe multisig expansion.',
    severity: 'Low',
    riskScore: 18,
    status: 'Cleared',
    chain: 'Base',
    confidence: 99,
  }
];

export const INITIAL_STABLECOINS: StablecoinMetric[] = [
  {
    id: 'STB-USDC',
    symbol: 'USDC',
    name: 'USD Coin (Circle)',
    price: 1.0001,
    depegRisk: 'Safe',
    trustScore: 99,
    backingRatio: 100.12,
    sentiment: 'Bullish',
    liquidity: 4250.00, // $4.25 Billion
    volatility: 0.02,
    chainStability: 98,
  },
  {
    id: 'STB-USDT',
    symbol: 'USDT',
    name: 'Tether USD (Tether)',
    price: 1.0003,
    depegRisk: 'Safe',
    trustScore: 91,
    backingRatio: 104.50,
    sentiment: 'Neutral',
    liquidity: 8100.00, // $8.1 Billion
    volatility: 0.05,
    chainStability: 94,
  },
  {
    id: 'STB-DAI',
    symbol: 'DAI',
    name: 'Dai (Maker/Sky)',
    price: 0.9996,
    depegRisk: 'Low',
    trustScore: 89,
    backingRatio: 114.20, // Overcollateralized multi-collateral
    sentiment: 'Neutral',
    liquidity: 950.00, // $950 Million
    volatility: 0.11,
    chainStability: 90,
  },
  {
    id: 'STB-PYUSD',
    symbol: 'PYUSD',
    name: 'PayPal USD (Paxos)',
    price: 1.0000,
    depegRisk: 'Safe',
    trustScore: 95,
    backingRatio: 100.05,
    sentiment: 'Bullish',
    liquidity: 320.00, // $320 Million
    volatility: 0.03,
    chainStability: 96,
  },
  {
    id: 'STB-EURC',
    symbol: 'EURC',
    name: 'Euro Coin (Circle)',
    price: 1.0820, // Peaked in USD terms (1 EUR = ~1.082 USD)
    depegRisk: 'Safe',
    trustScore: 98,
    backingRatio: 100.08,
    sentiment: 'Bullish',
    liquidity: 180.00, // $180 Million
    volatility: 0.35, // FX Volatility in USD terms
    chainStability: 97,
  }
];

export const INITIAL_REPORTS: ComplianceReport[] = [
  {
    id: 'REP-2026-Q1',
    name: 'Stablecoin Reserves Audited Tax Statement (Q1 2026)',
    type: 'Tax Filing',
    date: '2026-04-15',
    status: 'Verified',
    recipient: 'Internal Auditor & Delaware Revenue Authority',
    aiSummary: 'Certified report highlighting total corporate holdings against liabilities. Showcases full USD parity across all multi-chain reserves. Total stablecoin balances checked on-chain at $3,540,200. Paid $14,200 in L2 gas optimized operational corporate expenses.'
  },
  {
    id: 'REP-MICA-2026',
    name: 'StableMind MiCA Compliance Advisory Self-Assessment Report',
    type: 'MiCA Advisory',
    date: '2026-05-10',
    status: 'Verified',
    recipient: 'ESMA Regulatory Portal Filing Draft',
    aiSummary: 'Assessed automated transaction caps on EUR-denominated stablecoin EURC under current MiCA regulatory rules. Weekly merchant volume falls comfortably within the €200M non-threshold limit. Auto-monitoring active for Arbitrum and Polygon gas splits.'
  },
  {
    id: 'REP-VARA-05',
    name: 'Monthly Outflow Compliance Report for Dubai VARA',
    type: 'Vara Disclosure',
    date: '2026-05-18',
    status: 'Requires Review',
    recipient: 'VARA Compliance Portal Sandbox v2',
    aiSummary: 'A summary was generated for outbound payroll streams to contract structures in EMEA. Highlighted potential anomalies during standard manual address overrides inside the Base blockchain router. Manual review flagged for employee EMP-106.'
  }
];

export const GENERAL_MOCK_INSIGHTS = [
  "Move payroll to Base to reduce transactions fee fees by 72% based on base gas trends.",
  "Warning: USDT exposure on your Arbitrum and Ethereum multi-sigs currently exceeds your corporate safe limit threshold.",
  "Your idle corporate treasury of 450,000 DAI could generate up to 4.8% APY utilizing Circle Yield v2 vaults securely.",
  "Ethereum networks gas fees are highly elevated today (~42 Gwei), recommend scheduling non-urgent payouts after 23:00 UTC."
];
